### ISSUE TITLE
helptags not generated for plugins installed

### ISSUE THREAD

**Issue by cusxio** [wbthomason/packer.nvim#133]
I'm not sure how to debug/fix this, from the `runtimepath` it seems that the plugins are in the `runtimepath`

but when I run `:help sandwich`, I get `E149: Sorry, no help for sandwich`.

Do I need to manually run `:helptags` ?

---

`plugins.lua`:

```lua
return require('packer').startup(
  function()
    use {'wbthomason/packer.nvim', opt = true}
    use 'jiangmiao/auto-pairs'
    use {
      'machakann/vim-sandwich',
      config = function()
        vim.cmd("runtime macros/sandwich/keymap/surround.vim")
      end
    }
    use {
      'justinmk/vim-sneak',
      config = function()
        vim.g['sneak#label'] = 1
        vim.g['sneak#s_next'] = 1
      end
    }
  end
)
```

`runtimepath`:

```
runtimepath=~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,~/.local/share/nvim/site/pack/packer/start/vim-sneak,~/.local/share/nvim/site/pack/packer/start/vim-sandwich,~/.local/share/nvim/site/pack/packer
/start/vim-nightfly-guicolors,~/.local/share/nvim/site/pack/packer/start/vim-moonfly-colors,~/.local/share/nvim/site/pack/packer/start/vim-colors-plain,~/.local/share/nvim/site/pack/packer/start/tcomment_vim,~/.lo
cal/share/nvim/site/pack/packer/start/blue-moon,~/.local/share/nvim/site/pack/packer/start/auto-pairs,~/.local/share/nvim/site/pack/packer/opt/packer.nvim,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local
/Cellar/neovim/HEAD-5ce328d/share/nvim/runtime,/usr/local/Cellar/neovim/HEAD-5ce328d/share/nvim/runtime/pack/dist/opt/matchit,/usr/local/Cellar/neovim/HEAD-5ce328d/lib/nvim,~/.local/share/nvim/site/pack/packer/sta
rt/vim-sandwich/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
```

**Comment by wbthomason** [comment]
Fascinating! I took a look into this, and it seems that - for me - `start` plugins are having their helptags loaded, but not `opt` plugins. It seems that you're getting helptags for neither? Could you check if there are any tags for `auto-pairs`?

**Comment by wbthomason** [comment]
Actually, that was a foolish comment - I now see the helptags loaded for every plugin; the `opt` plugins just load their helptags once they get lazy-loaded.

Could you look inside the install dir for e.g. `vim-sandwich` (should be `~/.local/share/nvim/site/pack/packer/start/vim-sandwich`) and see if the `doc/` directory there contains a `tags` file? That should tell us if this is a problem with running `helptags` or something else.

**Comment by wbthomason** [comment]
Could you please update `packer` to c277d76 and run `PackerUpdate`? I fixed a small logic bug that could be causing this issue.

**Comment by cusxio** [comment]
Thank you for the quick turn around! 🙏🏻

> Could you look inside the install dir for e.g. vim-sandwich (should be ~/.local/share/nvim/site/pack/packer/start/vim-sandwich) and see if the doc/ directory there contains a tags file?

There isn't any `tags` file.

> Could you please update `packer` to [c277d76](https://github.com/wbthomason/packer.nvim/commit/c277d76264367d68c02230be1f32aa9aade45f41) and run `PackerUpdate`? I fixed a small logic bug that could be causing this issue.

And yes, https://github.com/wbthomason/packer.nvim/commit/c277d76264367d68c02230be1f32aa9aade45f41 fixed it.

running `PackerUpdate` alone doesn't fix it. I need to delete `~/.local/share/nvim/site/pack` and restart from scratch and run `PackerInstall`. Once I've done that, the `tags` file appears.

**Comment by wbthomason** [comment]
I'm glad to hear that c277d76 seems to have fixed things, but `PackerUpdate` alone should have fixed this (might've needed to run it twice - once to update `packer` itself, then close Neovim, reopen, and run again with the reloaded `packer`), but I think we can close this issue for now. Feel free to re-open if you're still having problems!
